In [1]:
# Login to Google Cloud
from google.colab import auth
import os
auth.authenticate_user()

# Set project to reincrypt
!gcloud config set project reincrypt

Updated property [core/project].


In [2]:
import numpy as np
from natsort import natsorted

def str_to_ndarray(str: str) -> np.ndarray:
    rows = str.split('\n')
    arr = np.ndarray((len(rows), len(rows[0].split())))

    for idx, row in enumerate(rows):
        arr[idx, :] = row.split()

    return arr

In [3]:
training_data_zip_file = "training_2022-10-23.zip"

In [ ]:
!gsutil -m cp gs://reincrypt_data_us/{training_data_zip_file} .
!unzip {training_data_zip_file}

In [4]:
training_data_dir = "/content/training/"

In [5]:
images = []

for curr in natsorted(os.listdir(training_data_dir)):
    for rimg in natsorted(os.listdir(os.path.join(training_data_dir, curr))):
        image = None
        with open(os.path.join(training_data_dir, curr, rimg), "r+") as r:
            rimg_content = r.read()
            tis = rimg_content.split("$")[0].strip()
            image = str_to_ndarray(tis)
        images.append(image)
images = np.array(images)

In [6]:
technical_indicators = [images[:, :, i].reshape((-1)) for i in range(32)]

In [7]:
technical_indicators

[array([ 0.,  6., 14., ..., 13.,  6.,  0.]),
 array([83., 53., 32., ..., 36., 18.,  0.]),
 array([ 0., 13., 33., ..., 11.,  4.,  0.]),
 array([ 0.,  0., 14., ...,  0.,  0.,  0.]),
 array([ 0.,  4., 19., ...,  2.,  2.,  0.]),
 array([ 0., 12., 24., ...,  2.,  0.,  0.]),
 array([ 1.,  0.,  5., ..., 31., 15.,  0.]),
 array([ 6.,  0.,  0., ..., 32., 15.,  0.]),
 array([ 0.,  4., 19., ...,  2.,  2.,  0.]),
 array([ 0.,  0., 47., ...,  0.,  0.,  0.]),
 array([255., 240., 221., ...,  11.,  15.,  19.]),
 array([255., 229., 177., ..., 239., 243., 247.]),
 array([255., 191., 144., ..., 186., 182., 178.]),
 array([  0.,  91., 154., ..., 186., 188., 190.]),
 array([255., 201., 162., ..., 113., 135., 139.]),
 array([92., 65., 16., ...,  0.,  0.,  0.]),
 array([255., 191., 144., ..., 186., 182., 178.]),
 array([15.,  0., 45., ..., 88., 92., 95.]),
 array([254., 254., 143., ..., 255., 255., 255.]),
 array([255., 224., 192., ...,  46.,  52.,  57.]),
 array([255.,  78.,  85., ..., 223., 221., 218.]),
 

In [8]:
from sklearn.cluster import KMeans

In [9]:
kmeans = KMeans(n_clusters=4, random_state=0).fit(technical_indicators)

In [10]:
kmeans.labels_

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1,
       3, 2, 2, 3, 3, 3, 2, 3, 2, 1], dtype=int32)